### ISSUE TITLE
Facebook: Redirects to localhost

### ISSUE THREAD

**Issue by tinonetic** [EasyAbp/Abp.LoginUi#1]
Hi,

1. I have a fresh **ABP 7.1.0** installation, installed using `abp new MyApplication -u angular -d ef -dbms MySQL`
2. Created the DB, ran the DB migrator, confirmed ABP tables and data were created
3. Ran it successfully - Swagger shows, no errors in log file (https://localhost:44343)
4. I opened up my `*HttpApiHostModule.cs` file
5. I followed the documentation from Microsoft: https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-7.0
6. **I used ngrok for a public address  and added that address to Facebook redirect config**
7. I added your nuget package `EasyAbp.Abp.LoginUi.Web` and the module dependency

The facebook icon shows when I go to `https://localhost:44343/account/login`

But when I click it, it doesn't redirect to my configured ngrok address in item 6), it always redirect to my local address 

Part of the URL parameters have the following:

scope=email,public_profile&response_type=code&redirect_uri=**https%3A%2F%2Flocalhost%3A44343%2F**signin-facebook

It says: **Sorry, something went wrong**. (see screenshot below)

Did I miss something?

I have done and redone this several times.

Do I have to manually specify the redirect URL? 

![image](https://user-images.githubusercontent.com/8109147/230859157-6c292041-b654-442d-bc7c-4dbac57515eb.png)

**Comment by gdlcf88** [comment]
Your issue has nothing to do with this UI module.

Recheck the Microsoft docs, and I believe you can fix it soon.

**Comment by tinonetic** [comment]
You were right, I rechecked an realised my mistake. 

Thank-you
